
export const images = [
  {id: "4",url:'https://free4kwallpapers.com/uploads/originals/2019/07/14/ultra-hd-ocean-s-wallpaper.jpg', avatar: require("./assets/avatar1.jpg")},
  {id: "18",url:'https://cdn.wallpapersafari.com/24/3/ZlgUc6.jpg', avatar: require("./assets/avatar2.jpg")},
  {id: "23",url:'https://www.dayglo.com/media/1212/bokeh-3249883_1280.png', avatar: require("./assets/avatar2.jpg")},
  {id: "102",url: require("./assets/post12.jpg"), avatar: require("./assets/avatar4.jpg")},
  {id: "16",url: require("./assets/post13.jpg"), avatar: require("./assets/avatar5.jpg")},
  {id: "44",url: require("./assets/post15.jpg"), avatar: require("./assets/avatar6.jpg")},
  {id: "7",url:'https://wallpaperplay.com/walls/full/b/5/e/159585.jpg', avatar: require("./assets/avatar2.jpg")},
  {id: "5",url:'https://upload.wikimedia.org/wikipedia/commons/e/e0/Long_March_2D_launching_VRSS-1.jpg', avatar: require("./assets/avatar2.jpg")},
  {id: "17",url:'https://cosmos-production-assets.s3.amazonaws.com/file/spina/photo/6597/180716_fluorescent_P.jpg', avatar: require("./assets/avatar2.jpg")},
  {id: "41",url: require("./assets/post16.jpg"), avatar: require("./assets/avatar3.jpg")},
  {id: "62",url: require("./assets/post23.jpg"), avatar: require("./assets/avatar3.jpg")},
  {id: "13",url:'https://c.gitcoin.co/grants/4e0e1e6de351af46fe9482b35840d3bd/logo.png', avatar: require("./assets/avatar2.jpg")},
  {id: "19",url:'https://images-na.ssl-images-amazon.com/images/I/81wajOO6mLL._SX355_.jpg', avatar: require("./assets/avatar2.jpg")},
  {id: "12",url:'https://www.melbourneairport.com.au/getattachment/Passengers/Parking/long-term-car-park/new-banner-homepage_02.png', avatar: require("./assets/avatar3.jpg")},
  {id: "10",url:'https://images.unsplash.com/photo-1490907452017-eccf91f84cf9', avatar: require("./assets/avatar3.jpg")},
  {id: "34",url: require("./assets/post1.jpg"), avatar: require("./assets/avatar1.jpg")},
  {id: "1",url:'https://i.pinimg.com/originals/0e/9e/88/0e9e8812f01f82650833264673bf51ed.jpg', avatar: require("./assets/avatar1.jpg")},
  {id: "2",url:'https://wallpaperaccess.com/full/7281.jpg', avatar: require("./assets/avatar1.jpg")},
  {id: "3",url:'https://images-na.ssl-images-amazon.com/images/I/71Tq9OsjO7L._SY879_.jpg', avatar: require("./assets/avatar1.jpg")},
  {id: "15",url: require("./assets/post10.jpg"), avatar: require("./assets/avatar2.jpg")},
  {id: "22",url: require("./assets/post11.jpg"), avatar: require("./assets/avatar3.jpg")},
  {id: "55",url: require("./assets/post14.jpg"), avatar: require("./assets/avatar3.jpg")},
  {id: "28",url: require("./assets/music1.jpeg"), avatar: require("./assets/avatar6.jpg")},
  {id: "223",url: require("./assets/chase-fade-Pb13EUxzMDw-unsplash.jpg"), avatar: require("./assets/avatar4.jpg")},
  {id: "49",url: require("./assets/post17.jpg"), avatar: require("./assets/avatar4.jpg")},
  {id: "381",url:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSoI7Yah5HYzaOn2tnpdBGdXgLL5Ka3ElFjYJPM7zZ91_WHw0TO', avatar: require("./assets/avatar3.jpg")},
]