require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Quantifi' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSharedElement', :path => '../node_modules/react-native-shared-element'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-track-player', :path => '../node_modules/react-native-track-player'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNReactNativeGetMusicFiles', :path => '../node_modules/react-native-get-music-files'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-music-control', :path => '../node_modules/react-native-music-control'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNBootSplash', :path => '../node_modules/react-native-bootsplash'

  pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'

  target 'QuantifiTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Quantifi-tvOS' do
  # Pods for Quantifi-tvOS

  target 'Quantifi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
